RxSwiftCommunity/Action

- Action.podspec
- AlertAction.swift
- Demo/Demo.xcodeproj/project.pbxproj
- Demo/Demo/Base.lproj/Main.storyboard
- Demo/Demo/ViewController.swift
- Demo/DemoTests/AlertActionTests.swift
- Demo/Podfile.lock
- Readme.md
Basically replicating https://github.com/artsy/eidolon/blob/f95c0a5bf1e90358320529529d6bf431ada04c3f/Kiosk/App/RACAlertAction.m
> Added UIAlertAction extension.

- Action.swift
- Demo/Podfile.lock
Fixes #3 by using RxSwift's newly included `createUnbounded()` factory
method for ReplaySubject.
> Use unbounded ReplaySubject

- Action.podspec
- Action.swift
- Demo/Demo/ViewController.swift
- Demo/DemoTests/ActionTests.swift
- Demo/DemoTests/AlertActionTests.swift
- Demo/DemoTests/BarButtonTests.swift
- Demo/DemoTests/ButtonTests.swift
- Demo/Podfile
- Demo/Podfile.lock
* Didn't affect us as we were already bridging it to an `Observable`.
Refs #18
> [WIP] Update to RxSwift 2.0

- Readme.md
As the title says (and AFAIK) there is no need anymore to include installation of `RxSwift` since it is a dependency and Rx 2.0 is not in beta anymore. Tested it on a few projects and also Demo project has only `Action` too, so should be fine. The text needed an update so feel free to improve it :laughing:
> Update installation, since Rx 2.0 is not in beta anymore.

- .travis.yml
- Action.swift
- Demo/DemoTests/ActionTests.swift
- Demo/DemoTests/ButtonTests.swift
- Demo/Podfile
- Demo/Podfile.lock
When button is deallocated, observable is not disposed.
So for example, if an application downloads some data from the internet and the user decides to cancel, download wont be stopped after uiviewcontroller is dismissed.
> fixed observable's disposing

- Action.xcodeproj/project.pbxproj
The run script was causing nested frameworks to be built which caused the errors below.
```
ITMS-90205: "Invalid Bundle. The bundle at 'app.app/Frameworks/Action.framework' contains disallowed nested bundles."
ITMS-90206: "Invalid Bundle. The bundle at 'app.app/Frameworks/Action.framework' contains disallowed file 'Frameworks'."
```
> Removed the carthage copy-frameworks run script

- Action.swift
- Demo/DemoTests/ActionTests.swift
Take a look at this approach, changing `Action<Void, Void>` to `Action<Void, AnyObject?>` seems to still maintain compatibility with UIButton's rx_action, however I'm still fairly new to RxSwift and Swift itself so I may not have the complete picture.
I've tested this and it allows me to use a pattern very similar to what I had been using in RAC where RACCommand had executionSignals.
If it's not quite right perhaps it'll be a nudge in the right direction :blush:
> Added executionObservables to provide a mechanism for observing work

- Readme.md
Updates README with a note on how to create an `Action` that emits download progress values.
related to this conversation https://github.com/RxSwiftCommunity/Action/issues/38
> Add note about CocoaAction and how to get download progress

- Action.podspec
- Action.swift
- Action.xcodeproj/project.pbxproj
- AlertAction.swift
- Cartfile
- Cartfile.resolved
- Demo/Demo.xcodeproj/project.pbxproj
- Demo/Demo/AppDelegate.swift
- Demo/DemoTests/ActionTests.swift
- Demo/DemoTests/ButtonTests.swift
- Demo/Podfile
- Demo/Podfile.lock
- UIBarButtonItem+Action.swift
- UIButton+Rx.swift
I have started the process of converting to Swift 3. 
This requires `RxSwift`/`RxCocoa` to be stable, which won't happen for some weeks. 
I have converted the Action project and made it build using the `RxSwift` develop branch. When proper beta/rc are available we should update to those. 
As of 9th of September, the Demo project is not compiling, as the Podfile cannot use a specific branch. 
I will keep updating this PR as `RxSwift` releases new candidates.  
Feel free to contribute or comment.
> [WIP] Converting to Swift 3

- Action+Internal.swift
- Action.swift
- Action.xcodeproj/project.pbxproj
- Action.xcworkspace/xcshareddata/Action.xcscmblueprint
- AlertAction.swift
- Cartfile
- Cartfile.resolved
- Demo/ViewController.swift
- Tests/Action/AlertActionTests.swift
- Tests/Action/BarButtonTests.swift
- Tests/Action/ButtonTests.swift
- UIBarButtonItem+Action.swift
- UIButton+Rx.swift
Changes `rx_action` to `rx.action`.
Fixes #50.
WIP because setting is currently borked. Consider:
```swift
button.rx.action = Action(...)
```
This produces an error `cannot assign to property 'rx' is get-only`. `rx` is a get-only property that is a struct value-type, which is causing the compiler to mix up. There's probably an easy way around this, I'm going to look through the RxSwift code to find it.
> New Rx style

- Action.xcodeproj/project.pbxproj
- Tests/Action/ActionTests.swift
This PR fixes following warnings:
- Tests/Action/ActionTests.swift:296:25: Variable 'observer' was written to, but never read
- ld: warning: directory not found for option '-FCarthage/Checkouts/RxSwift/build/Debug'
> Fix build warnings

- Action.swift
- AlertAction.swift
- Tests/Action/ActionTests.swift
- UIBarButtonItem+Action.swift
- UIButton+Rx.swift
This PR refactors internal implementation to focus more on observables.
No public APIs are changed, and all existing test cases are retained.
The changes minimize:
- Use of private subjects
- Stored properties that manage state
- Manual locking
If we should avoid significant internal changes in this minor version, I'll work for the next major version.
> Refactor internal implementation and add more test cases

- Readme.md
- Sources/Action/Action+Internal.swift
- Sources/Action/Action.swift
- Sources/Action/UIKitExtensions/AlertAction.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIButton+Rx.swift
Updated documentation from `rx_action` to `rx.action`.
Fixes #52.
> Update documentation for rx.action

- Sources/Action/Action.swift
- Tests/ActionTests/ActionTests.swift
I found second call of `execute()` returns the same output which the first time returned.
This issue started to happen from version 2.1.0, and doesn't happen when one use `input` only.
This issue is caused by replaying execution observable. To fix this issue, this PR replaces `sharedReplay(1)` of `executionObservable` with `share()` so that `execute()` returns always return the latest execution observable.
I'm sorry for overlooking this issue.
I've also update unit tests to detect the same kind of issue.
> Not replay executionObservables for execute()

- Sources/Action/Action.swift
Rewrote the `executing` observable, leading to simpler code.
Also Integrated @stefanomondomino's idea of using a `shareReplay(1)` to guarantee that late subscribers get the current execution state.
> Rewrite executing observable

- Action.xcodeproj/project.pbxproj
- Demo/Base.lproj/Main.storyboard
- Demo/ViewController.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIButton+Rx.swift
- Sources/Action/UIKitExtensions/UIControl+Rx.swift
- Tests/ActionTests/BindToTests.swift
- Tests/ActionTests/ButtonTests.swift
Mergers #70.
I was initially confused about how to use this, and the Demo came in handy! I'm definitely a fan of this approach, great work @stefanomondino!
A remaining question: should the `action` parameter in `bindTo()` functions be optional?
We should also update our readme once this is merged :wink:
> Adds tests + formatting for bindTo()

- Action.xcodeproj/project.pbxproj
- Demo/Base.lproj/Main.storyboard
- Demo/ViewController.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIButton+Rx.swift
- Sources/Action/UIKitExtensions/UIControl+Rx.swift
bindToAction: quick way to bind a common action to a button with a input transform
As discussed in #17 , here's my idea for _something_ that should allow a control (a UIButton or UIBarButtonItem, but it could be extended)
I've updated the example with three more buttons that are connected to the same action while giving three distinct inputs. No CocoaActions are involved at all. I'm afraid naming needs review :(
> bindToAction

- Sources/Action/Action.swift
This PR rewrites both the creation of Action's `error` observable inside the Action itself and restructures error handling in the `execute` function.
The motivation is to try and fix #63. The only plausible reason that could explain this issue is that the `notEnabledError` observable previously created was derived from `inputs`. Since `executionObservable` (the root observable for all other work inside action) was derived from `inputs` too, one couldn't guarantee the order of processing on `input` update, depending on who subscribed to what and in what order.
To fix the issue, I decided to have a single point of contact with `inputs`, and derive everything from it. This led to some not-perfectly-Rx-y code where I push errors to an internal subject using side effects, but it really is less …
> Rewrite errors observable

- Action.xcodeproj/project.pbxproj
- Changelog.md
This removes the unused `RxBlocking` dependency in the `Action` target. We found that issue while including it into our project and it suddenly required `RxBlocking` as well. Looking at the code there should actually be no need for it. Tests and Demo app run without issue with the library removed.
> Remove RxBlocking from Linked Libraries

- Cartfile
- Cartfile.resolved
- Package.swift
- Readme.md
@freak4pc  After I updated RxSwift version to ~> 3.3.0, I came across this Error below that two of the symbols existed in RxSwift 3.0 are missing from 3.3.0. Apps crash when launching. There were apparently some breaking changes in RxSwift, even though it was a minor update. (I'm not sure this issue should be reported to Action or RxSwift)
```
dyld: lazy symbol binding failed: Symbol not found: __TIFE7RxSwiftPS_14ObservableType2doFT6onNextGSqFzwx1ET__7onErrorGSqFzPs5Error_T__11onCompletedGSqFzT_T__11onSubscribeGSqFT_T__9onDisposeGSqFT_T___GCS_10ObservablewxS1__A_
Referenced from: /Users/yuzushioh/Library/Developer/CoreSimulator/Devices/0A21E317-EC22-42DB-BFEE-FCA12FC64084/data/Containers/Bundle/Application/30C85070-03A8-40EE-9F36-96221E753330/MyApp.app/Frameworks/Action.framework/Action …
```
> App crashes because of missing symbols, using RxSwift 3.3.0

- Action.podspec
- Cartfile
- Cartfile.resolved
- Changelog.md
- Demo/ViewController.swift
- Package.swift
- Sources/Action/Action.swift
- Sources/Action/UIKitExtensions/AlertAction.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIButton+Rx.swift
- Sources/Action/UIKitExtensions/UIControl+Rx.swift
- Tests/ActionTests/ActionTests.swift
- Tests/ActionTests/BindToTests.swift
Resolves #86 
I'd appreciate a close eye here as I haven't touched a) this repo or 2) Carthage in a little while 🙇
> Resolve deprecations related to `bindTo` and update Action's API to match

- .travis.yml
- Action.xcodeproj/project.pbxproj
- Action.xcodeproj/xcshareddata/xcschemes/Action-macOS.xcscheme
- Action.xcodeproj/xcshareddata/xcschemes/Action-tvOS.xcscheme
- Action.xcodeproj/xcshareddata/xcschemes/Action-watchOS.xcscheme
- Sources/Action/Action.h
Added separated targets for each platforms. Module import name is `Action`.
- Action-macOS
- Action-tvOS
- Action-watchOS
Also updated `.travis.yml` to add build check for each platforms.
> Add Carthage Support for macOS, tvOS and watchOS

- Demo/ViewController.swift
- Sources/Action/Action.swift
- Sources/Action/UIKitExtensions/AlertAction.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIButton+Rx.swift
- Sources/Action/UIKitExtensions/UIControl+Rx.swift
- Tests/ActionTests/ActionTests.swift
- Tests/ActionTests/AlertActionTests.swift
- Tests/ActionTests/BarButtonTests.swift
- Tests/ActionTests/ButtonTests.swift
`addDisposableTo()` method should be deprecated in the future. I modified it to the recommended method `disposed(by:)` .
https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Deprecated.swift#L46
> addDisposableTo() to disposed(by:)

- Action.xcodeproj/project.pbxproj
- Changelog.md
Missing sources in the target of watchOS.
I think that can not use Carthage etc, so I fixed it.
> Fix missing watchOS target compile sources

- Action.podspec
- Changelog.md
Since a relatively important change was made (changing PublishSubject to the new InputSubject by @Econa77) , I felt like this calls for a new version. 
I believe I don’t have permissions to push this up to CocoaPods, so would probably need your help here @ashfurrow
> Version bump to 3.1.0

- Action.podspec
- Cartfile
- Sources/Action/Action.swift
- Updates for RxSwift release candidate `rc-0`
- change `shareReplay(1)` to use the new API `share(replay: 1, scope: .forever)`
> RxSwift 4.0.0-rc0

- Action.podspec
- Cartfile
> RxSwift 4.0.0 target

- Action.podspec
- Cartfile
- Changelog.md
> Release version `3.4.0`

- .travis.yml
- Action.xcodeproj/project.pbxproj
- Cartfile.resolved
> Carthage patch

- Changelog.md
- Sources/Action/Action.swift
- Tests/ActionTests/ActionTests.swift
This PR closes #123 
- Adds convenience initialiser that takes a work factory returning `ObservableConvertibleType`. This allows constructing Actions with work factory returning;
- `PrimitiveSequence` such as `Single`, `Completable`, etc.
- `SharedSequence` such as `Driver`
- Adds type alias `CompletableAction`.
- An action with a work factory returning a `Completable`
- Its `elements` will emit no next events
> Allow work factories with other return types than `Observable`

- .gitmodules
Hello, 
Since the commit b49959c646fcac567a4b0cfe87dad7b14b343300, this is not working for carthage anymore.
I got the error: "Parse error: expected submodule commit SHA in output of task (ls-tree -z 9c413d35c3b0f14dd2a817c866415afd9a40e4db Carthage/Checkouts/RxSwift) but encountered: "
After some research, apparently, it's because the submodules have been removed.
https://github.com/Carthage/Carthage/issues/135
So, removing the .gitmodules file should do the job.
> [Fix][Carthage] Remove Submodules file

- Changelog.md
- Demo/ViewController.swift
- Readme.md
- Sources/Action/Action.swift
- Sources/Action/CommonUI/Button+Action.swift
- Sources/Action/CommonUI/Control+Action.swift
- Sources/Action/UIKitExtensions/UIAlertAction+Action.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Tests/ActionTests/ActionTests.swift
This PR is a first phase of public API cleanup as discussed on #120, it includes the following;
- Rename `enabled` ~> `isEnabled`
- Rename  `executing` ~> `isExecuting`
- Deprecate renamed properties
- Remove unnecessary properties from public API; `workFactory` and `_enabledIf`
> Improve naming of public API properties

- Action.podspec
- Action.xcodeproj/project.pbxproj
- Cartfile
- Cartfile.resolved
- Changelog.md
- Sources/Action/UIKitExtensions/UIAlertAction+Action.swift
I've also already updated the Podspec to 3.7 for future cocoapods release
Fixes #150. Fixes #152.
> Compatibility with Swift 4.2

- Action.xcworkspace/contents.xcworkspacedata
- Cartfile.resolved
- Changelog.md
same reason as https://github.com/RxSwiftCommunity/RxDataSources/issues/237
> Fix build failure on New Build System (default on Xcode 10)

- Action.podspec
- Changelog.md
RxSwift, RxCocoa are defined too strict, Action no longer works with RxSwift, RxCocoa 4.4 because of this.
> Less restrictive dependency definitions

- Changelog.md
- Sources/Action/Action.swift
- Sources/Action/UIKitExtensions/UIAlertAction+Action.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
Hey guys :))
This is a simple syntax sugar when Input is Void, so we can call `execute()` instead of always `execute(())` with the ().
> Syntax sugar to execute when Input is Void.

- Action.podspec
This is required since RxSwift raised minimum deployment target to WatchOS 3.0 as discussed in #173
> Update WatchOS minimum deployment target to 3.0

- Action.podspec
- Action.xcodeproj/project.pbxproj
- Changelog.md
- Sources/Action/Action+Extensions.swift
- Sources/Action/Action.swift
- Tests/ActionTests/ActionTests.swift
- Tests/iOS-Tests/BindToTests.swift
- Tests/iOS-Tests/ButtonTests.swift
- Tests/iOS-Tests/RefreshControlTests.swift
Hi all I hope this should close [PR issue 168](https://github.com/RxSwiftCommunity/Action/pull/163) So I went for a KISS solution.
> Extracting Errors

- Tests/iOS-Tests/AlertActionTests.swift
- Tests/iOS-Tests/BarButtonTests.swift
- Tests/iOS-Tests/ButtonTests.swift
- Tests/iOS-Tests/RefreshControlTests.swift
Hi all,
I update syntax sugar to ｀execute｀ in iOS-Test.
This is a simple test. 😀
related Pull Request #171
> 【Test】Syntax sugar to `execute` when Input is Void in iOS-Tests

- Changelog.md
- Sources/Action/Action+Extensions.swift
- Tests/ActionTests/ActionTests.swift
This PR fixes #189, it introduces a new observable property to `CompletableAction` extension which will emit a next event every time underlying work factory completes.
> Add `completions` property to `CompletableAction`

- Action.xcodeproj/project.pbxproj
- Changelog.md
There's still references to RxAtomic in the project ([this happened with RxSwift as well](https://github.com/ReactiveX/RxSwift/pull/1919)). The references were removed and the project was also migrated to use Swift 5.
> Remove RxAtomic references

- Action.xcodeproj/project.pbxproj
- Tests/ActionTests/ActionTests.swift
- Tests/Nimble+RxTest+Ext.swift
- Tests/TestEvents.swift
- Tests/iOS-Tests/AlertActionTests.swift
- Tests/iOS-Tests/BarButtonTests.swift
I just wanted to re-order the `ActionTests` and to fully use `Quick+Nimble` matchers where possible and to avoid totally `XCT`
> Nimble specs

- Action.xcodeproj/project.pbxproj
Add `RxCocoa.framework` in `Link Binary With Libraries`.
> chore: add missing dependency

- Action.podspec
- Cartfile
- Cartfile.resolved
- Changelog.md
- Package.resolved
- Package.swift
- Tests/Nimble+RxTest+Ext.swift
- circle.yml
RxSwift 6 (as of [6.0.0-rc.1](https://github.com/ReactiveX/RxSwift/releases/tag/6.0.0-rc.1)) doesn't introduce any source-breaking changes that affect Action, so it's safe to extend our version compatibility to include both RxSwift 5 and 6.
> Add support for RxSwift 6

- Changelog.md
- Sources/Action/CommonUI/Control+Action.swift
- Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift
- Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift
- Tests/iOS-Tests/BindToTests.swift
https://github.com/RxSwiftCommunity/Action/issues/227
This pull request breaks the retain cycle in the various `bind(to:input:)` methods. Tests have also been added to ensure no retain cycle is introduced by calling `bind(to:input:)`.
> breakRetainCycle: Break retain cycle in bind(to:input:)

- Sources/Action/Action.swift
#trivial
replace `catchError` with `catch`
> Fixing deprecated warnings

- Changelog.md
- Sources/Action/Action.swift
#trivial
- `errorsSubject` and `inputsSubject` call only `onNext(_ element:)` 
- Replaced from `PublishSubject` to `PublishRelay `
> Use PublishRelay instead of PublishSubject

- Changelog.md
- Sources/Action/Action+Extensions.swift
- Tests/ActionTests.swift
**Problem statement**
`CompletableAction` is usually used in some repeatable manner. Each action can finish with an error especially if there's a network request or a validation process inside the `workFactory`. So far `completions` emits these errors which in turn disposes existing subscriptions to this observable.
**Proposed solution**
Catch errors in `completions`.
#trivial
> Filter out errors from `CompletableAction.completions`
