RxSwiftCommunity/Action

Action.podspec, Changelog.md, UIButton+Rx.swift
=> Added tvOS support

Readme.md
Removes warning about a limited ReplaySubject now that #3 has been fixed.
=> Remove warning from README

Action.podspec
Maybe it's is the better choice. @ashfurrow I'm sorry for my last PR, I've learn a lot over this the last week.
=> correct long term version of RxSwift/RxCocoa

.gitignore, Cartfile.resolved
- Add `Cartfile.resolved` (the equivalent of `Podfile.lock` in CocoaPods).
- Exclude `Carthage/Checkouts` from Git version control.
=> Update Carthage configurations

Action.podspec, Changelog.md
Updating changes necessary from the 1.3.0 release on Swift 2.3. Pushing the podspec now.
=> 1.3.0 release

Action.podspec, Changelog.md, Sources/Action/Info.plist
This release contains recent refactoring such as #56, #58 and #59.
=> 2.1.0 release

Readme.md, Sources/Action/Action.swift
In this PR
- Added some documentation about Action since it was marked as TODO
- Added carthage installation steps in Installation section in README
=> Added some documentation about Action and carthage installation to Readme

Sources/Action/UIKitExtensions/AlertAction.swift
rxFatalError is internal RxSwift func
=> Replaced rxFatalError with fatalError

Action.xcodeproj/project.pbxproj, Sources/Action/Action.swift, Sources/Action/InputSubject.swift, Tests/InputSubjectTests.swift
=> Replace PublishSubject

Action.podspec, Cartfile, Cartfile.resolved, Changelog.md
=> Require Rx 3.4

.gitignore, Readme.md, bin/bootstrap, bin/bootstrap-if-needed, circle.yml
Fixes #117. CI times down to ~2 minutes. Anyone up for review?
=> Migrates to CircleCI

Action.xcodeproj/project.pbxproj, Changelog.md, Demo/Base.lproj/Main.storyboard, Demo/ViewController.swift, Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift, Tests/iOS-Tests/BindToTests.swift, Tests/iOS-Tests/RefreshControlTests.swift
This PR should address #141 
I've updated the demo project to see it working, including a simple scrollview with a UILabel with a lot of bottom padding.
Thoughts?
=> UIRefreshControl support

Action.podspec, Action.xcodeproj/project.pbxproj, Action.xcodeproj/xcshareddata/xcschemes/Action-macOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action-tvOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action-watchOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme, Action.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Cartfile, Cartfile.resolved, Changelog.md, Demo/Info.plist, Readme.md, Sources/Action/Info.plist, Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift, Tests/ActionTests/ActionTests.swift
=> Semantic  versioning 

Action.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Changelog.md, Demo/ViewController.swift, Readme.md, Sources/Action/Action.swift, Sources/Action/CommonUI/Button+Action.swift, Sources/Action/CommonUI/Control+Action.swift, Sources/Action/UIKitExtensions/UIAlertAction+Action.swift, Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift, Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift, Tests/ActionTests/ActionTests.swift
Reverts RxSwiftCommunity/Action#160
=> Revert "Prepare for version 4.0"

Sources/Action/Action.swift
=> Style-guide typo fixed. #trivial

Action.podspec, Changelog.md
=> Podspec preparation 

Action.xcodeproj/project.pbxproj, Action.xcodeproj/xcshareddata/xcschemes/Action-macOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action-tvOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action-watchOS.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Action.xcscheme, Action.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme, Cartfile, Cartfile.resolved, Sources/Action/Action+Extensions.swift, Sources/Action/Action+Internal.swift, Sources/Action/CommonUI/Button+Action.swift, Sources/Action/CommonUI/Control+Action.swift, Sources/Action/InputSubject.swift, Sources/Action/UIKitExtensions/UIAlertAction+Action.swift, Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift, Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift, circle.yml
Migrating to the new version of Xcode and Swift :))
=> Migrating to Swift 5 Xcode 10.2

.gitignore, Action.podspec, Package.resolved, Package.swift, Sources/Action/UIKitExtensions/UIAlertAction+Action.swift, Sources/Action/UIKitExtensions/UIBarButtonItem+Action.swift, Sources/Action/UIKitExtensions/UIRefreshControl+Action.swift
Just updating dependencies to Rx 4.5.0 :))
=> Updating spm syntax to new swift-tools

Demo/Base.lproj/Main.storyboard, Demo/ViewController.swift
=> Fix demo application warning

Action.xcodeproj/project.pbxproj, Tests/ActionTests.swift, Tests/ActionTests/ActionTests.swift, Tests/iOS-Tests/AlertActionTests.swift, Tests/iOS-Tests/BarButtonTests.swift, Tests/iOS-Tests/BindToTests.swift, Tests/iOS-Tests/ButtonTests.swift, Tests/iOS-Tests/RefreshControlTests.swift
The indentation was one on the most un explainable mysteries from `Xcode`. It's all fixed at the moment and in line with gitHub viewing.
=> Rxblocking removal

Readme.md
I updated Action version of Carthage in Readme.md
=> Update version in Readme.md

Readme.md
Updated Readme to include `completions`
=> Updated Readme to include completions

circle.yml
Also Prettier cleaned up the yaml file and I liked the changes enough to commit them 🤷‍♂️ 
Fixes #219.
=> Updates Xcode to 11.3 on CI

Action.xcodeproj/project.pbxproj, Cartfile.resolved
=> Fix Carthage build error
